### ISSUE TITLE
[ REQUEST ] -- Service "Collected" bool

### ISSUE THREAD

**Issue by Fiskey111** [LtFlash/LtFlash.Common#1]
I would like to request a "collected" bool for services as well (preferably when the service is being dismissed: e.g. line 227 of [https://github.com/LtFlash/LtFlash.Common/blob/master/LtFlash.Common/EvidenceLibrary/Services/EMS.cs](url). That way I can display Game.DisplayHelp("string") when the service is done to give the player instructions.  (Specifically when EMS leaves and the victim is dead the player will receive a tip to call the coroner.

Thanks!

**Comment by LtFlash** [comment]
I think about 2 things:
1. `bool IsCollected { get; }` which returns true when a dialogue npc-player is finished. (Waiting with this till Dispose() might cause issues)
2. `string MsgIsCollected { set; }` + optional help box, displayed when this != string.Empty.
   These two should reduce unnecessary lines in your code.

**Comment by Fiskey111** [comment]
Either of those work for me!  I don't mind having to create the help, but if you want to go route 2 then that works for me!
Note this isn't a vital issue -- it's just something I noticed when I did a play through!

**Comment by LtFlash** [comment]
Both of them will be implemented along with an `ICollectable` interface.

**Comment by LtFlash** [comment]
Implemented.
